name: recap
recipe: drupal8
config:
  php: '7.4'
  webroot: .
  composer_version: '1.10.7'
services:
  appserver:
    build:
      - composer install
  node:
    type: 'node:6.15'
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node