name: recap
recipe: drupal9
config:
  php: '8.1'
  via: nginx
  webroot: .
services:
  appserver:
    build:
      - composer install
  node:
    type: node
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
