editor.editor.*.third_party.editor_file:
  type: mapping
  label: 'Editor File upload settings'
  mapping:
    status:
      type: boolean
      label: 'Status'
    scheme:
      type: string
      label: 'File storage'
    directory:
      type: string
      label: 'Upload directory'
    extensions:
      type: string
      label: 'Allowed file extensions'
    max_size:
      type: string
      label: 'Maximum file size'
