name: 'Testing config import'
type: profile
description: 'Tests install profiles in the config importer.'
# version: VERSION
# core: 8.x
hidden: true
install:
  - syslog
themes:
  - stark

# Information added by Drupal.org packaging script on 2018-11-07
version: '8.6.3'
core: '8.x'
project: 'drupal'
datestamp: 1541602730
