name: Testing config overrides
type: profile
description: 'Minimal profile for running tests with config overrides in a profile.'
# version: VERSION
core: 8.x
hidden: true
install:
  - action
  - language
  - tour

# Information added by Drupal.org packaging script on 2020-03-18
version: '8.7.12'
project: 'drupal'
datestamp: 1584552285
