_core:
  default_config_hash: 2z_THKqotLn7-Fl5rKmZkNmZph-IVfv-8q1ShRZAqBY
login_link_enabled: false
login_link_label: 'CAS Login'
login_success_message: 'You have been logged in.'
server:
  version: '2.0'
  protocol: https
  hostname: fed.princeton.edu
  port: 443
  path: /cas
  verify: 0
  cert: ''
gateway:
  check_frequency: -2
  paths:
    id: request_path
    negate: false
    pages: ''
forced_login:
  enabled: true
  paths:
    id: request_path
    negate: false
    pages: /user/login
user_accounts:
  prevent_normal_login: false
  auto_register: false
  email_assignment_strategy: 0
  email_hostname: ''
  email_attribute: ''
  auto_assigned_roles: {  }
  restrict_password_management: true
  restrict_email_management: true
error_handling:
  message_validation_failure: 'There was a problem logging in, please contact a site administrator.'
  message_no_local_account: 'There was a problem logging in, please contact a site administrator.'
  message_subscriber_denied_reg: 'There was a problem logging in, please contact a site administrator.'
  message_subscriber_denied_login: 'There was a problem logging in, please contact a site administrator.'
  message_account_blocked: 'There was a problem logging in, please contact a site administrator.'
  message_username_already_exists: 'There was a problem logging in, please contact a site administrator.'
  message_prevent_normal_login: 'This account must log in using <a href="[cas:login-url]">CAS</a>.'
  message_restrict_password_management: 'The requested account is associated with CAS and its password cannot be managed from this website.'
logout:
  cas_logout: false
  logout_destination: ''
  enable_single_logout: false
  single_logout_session_lifetime: 25
proxy:
  initialize: false
  can_be_proxied: false
  proxy_chains: ''
advanced:
  debug_log: false
  connection_timeout: 10
