<?php

/**
 * @file
 * Allows support of a new view handler.
 */


/**
 * Implements hook_theme().
 */
function jssor_theme() {
  return array(
    'jssor' => array(
      'variables' => array(
        'view' => NULL,
        'rows' => NULL,
      ),
      'file' => 'jssor.theme.inc',
    ),
  );
}


/**
 * Implements hook_views_pre_render().
 */
function jssor_views_pre_render($view) {
  if ($view->storage->id() === 'test') {
    //$view->element['#attached']['js'][] = array('type' => 'setting', 'data' => $settings);
    //$view->element['#attached']['library'][] = 'views/views.ajax';
  }

  return $view;
}
